package ru.fcref.system.domain;

public enum EventType {
    INVITATION_CREATED,
    INVITATION_ACTIVATED,
    CANDIDATE_REGISTERED,
    REGULATION_CHANGED,
    STAGE_ASSIGNED,
    STAGE_RESULT_SUBMITTED,
    VERDICT_RECORDED,
    VOTE_OPENED,
    VOTE_CAST,
    VOTE_CLOSED,
    COMPLAINT_CREATED,
    CANDIDATE_BLOCKED,
    CANDIDATE_UNBLOCKED,
    ROLE_ASSIGNED,
    ROLE_REVOKED
}
